### ISSUE TITLE
Error when clicking "Submit Phone Number" on verification screen

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1275]
## The Issue
When clicking "Submit Phone Number" on verification screen, you get a green screen and console error:

```
Uncaught ReferenceError: Submit is not defined
    at t.value (file:///C:/Program%20Files/LBRY/resources/app.asar/renderer.js:1:420682)
    at finishClassComponent (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:8307:33)
    at updateClassComponent (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:8275:12)
    at beginWork (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:8896:16)
    at performUnitOfWork (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11708:16)
    at workLoop (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11731:26)
    at HTMLUnknownElement.callCallback (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:104:14)
    at Object.invokeGuardedCallbackDev (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:142:16)
    at invokeGuardedCallback (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:191:29)
    at replayUnitOfWork (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11218:7)
    at renderRoot (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11773:11)
    at performWorkOnRoot (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12318:24)
    at performWork (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12239:9)
    at performSyncWork (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12216:5)
    at interactiveUpdates (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12466:9)
    at interactiveUpdates (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:1962:10)
C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9557 The above error occurred in the <t> component:
    in t (created by Connect(t))
    in Connect(t) (created by t)
    in section (created by t)
    in div (created by t)
    in div (created by ModalPortal)
    in div (created by ModalPortal)
    in ModalPortal (created by Modal)
    in Modal (created by t)
    in t (created by t)
    in t (created by Connect(t))
    in Connect(t) (created by t)
    in t (created by Connect(t))
    in Connect(t) (created by t)
    in div (created by t)
    in main (created by t)
    in div (created by t)
    in t (created by Connect(t))
    in Connect(t)
    in div
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9557
C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12300 Uncaught ReferenceError: Submit is not defined
    at t.value (file:///C:/Program%20Files/LBRY/resources/app.asar/renderer.js:1:420682)
    at finishClassComponent (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:8307:33)
    at updateClassComponent (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:8275:12)
    at beginWork (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:8896:16)
    at performUnitOfWork (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11708:16)
    at workLoop (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11731:26)
    at renderRoot (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11762:9)
    at performWorkOnRoot (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12318:24)
    at performWork (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12239:9)
    at performSyncWork (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12216:5)
    at interactiveUpdates (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12466:9)
    at interactiveUpdates (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:1962:10)
    at dispatchInteractiveEvent (C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:4256:3)
```
### Steps to Reproduce
1.
2.
3.

### Expected Behaviour
Tell us what should happen.

### Actual Behaviour
Tell us what happens instead.

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
@seanyesmunt new error when clicking verify after entering code. The network calls look fine. 


```
C:\Program Files\LBRY\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9557 The above error occurred in the <t> component:
    in t (created by Connect(t))
    in Connect(t)
    in Unknown (created by Connect(Component))
    in Connect(Component) (created by t)
    in div (created by t)
    in main (created by t)
    in div (created by t)
    in t (created by Connect(t))
    in Connect(t)
    in div
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```
