### ISSUE TITLE
Incompatible daemon modal missing in redesign

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1419]
## The Issue
The incompatible protocol warning modal is not showing up, you just get a blank green screen that sits on "waiting for name resolution".

https://github.com/lbryio/lbry-app/blob/95a85300dcbc5b5ed96e5f9dd8f5f3c67da147b2/src/renderer/modal/modalIncompatibleDaemon/view.jsx

### Steps to Reproduce
1. Insert 19.2 daemon into [resources/static/daemon directory](https://lbry.io/faq/lbry-directories)
2. run LBRY app

### Expected Behaviour
Tell us what should happen.

### Actual Behaviour
Tell us what happens instead.

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by nikooo777** [comment]
i noticed that when you claim a reward you don't get a popup anymore, nothing at all happens. could this be related?

**Comment by tzarebczan** [comment]
There is only a popup for the first reward, which is also broken. Other rewards havr snack bars that disappear... Can you double check?

**Comment by tzarebczan** [comment]
This is what I'm seeing in console on Master now:
```
Uncaught (in promise) TypeError: Cannot read property 'INCOMPATIBLE_DAEMON' of undefined
    at SplashScreen.render (webpack-internal:///./src/renderer/component/splash/view.jsx:152:47)
    at finishClassComponent (C:\Users\SoloDolo\Desktop\new5\lbry-app\node_modules\react-dom\cjs\react-dom.development.js:8389:33)
    at updateClassComponent (C:\Users\SoloDolo\Desktop\new5\lbry-app\node_modules\react-dom\cjs\react-dom.development.js:8357:12)
    at beginWork (C:\Users\SoloDolo\Desktop\new5\lbry-app\node_modules\react-dom\cjs\react-dom.development.js:8982:16)
    at performUnitOfWork (C:\Users\SoloDolo\Desktop\new5\lbry-app\node_modules\react-dom\cjs\react-dom.development.js:11814:16)
    at workLoop (C:\Users\SoloDolo\Desktop\new5\lbry-app\node_modules\react-dom\cjs\react-dom.development.js:11843:26)
    at renderRoot (C:\Users\SoloDolo\Desktop\new5\lbry-app\node_modules\react-dom\cjs\react-dom.development.js:11874:9)
    at performWorkOnRoot (C:\Users\SoloDolo\Desktop\new5\lbry-app\node_modules\react-dom\cjs\react-dom.development.js:12449:24)
    at performWork (C:\Users\SoloDolo\Desktop\new5\lbry-app\node_modules\react-dom\cjs\react-dom.development.js:12370:9)
    at performSyncWork (C:\Users\SoloDolo\Desktop\new5\lbry-app\node_modules\react-dom\cjs\react-dom.development.js:12347:5)
    at requestWork (C:\Users\SoloDolo\Desktop\new5\lbry-app\node_modules\react-dom\cjs\react-dom.development.js:12247:7)
    at scheduleWorkImpl (C:\Users\SoloDolo\Desktop\new5\lbry-app\node_modules\react-dom\cjs\react-dom.development.js:12122:13)
    at scheduleWork (C:\Users\SoloDolo\Desktop\new5\lbry-app\node_modules\react-dom\cjs\react-dom.development.js:12082:12)
    at Object.enqueueSetState (C:\Users\SoloDolo\Desktop\new5\lbry-app\node_modules\react-dom\cjs\react-dom.development.js:6644:7)
    at SplashScreen.Component.setState (C:\Users\SoloDolo\Desktop\new5\lbry-app\node_modules\react\cjs\react.development.js:238:16)
    at SplashScreen._updateStatusCallback (webpack-internal:///./src/renderer/component/splash/view.jsx:79:14)
webpack-internal:///./node_modules/webpack-dev-server/client/index.js?http://localhost:9080:77 [WDS] 
```
