### ISSUE TITLE
Error downloading lbry://hitmans-bodyguard-trailer 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#174]
## The Issue
Cannot download lbry://hitmans-bodyguard-trailer
### Steps to reproduce
1. Go to lbry://hitmans-bodyguard-trailer
2. Download
3. nothing, see error in log:
2017-06-01 00:44:45,746 INFO     lbrynet.lbrynet_daemon.Downloader:103: Download lbry://hitmans-bodyguard-trailer status changed to running
2017-06-01 00:44:45,746 CRITICAL twisted:154: Unhandled error in Deferred:
2017-06-01 00:44:45,746 CRITICAL twisted:154: 
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
  File "site-packages\lbrynet\lbrynet_daemon\Downloader.py", line 190, in download
  File "site-packages\lbrynet\lbrynet_daemon\Downloader.py", line 70, in download_path
  File "ntpath.py", line 85, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10: ordinal not in range(128

### Expected behaviour
Downloads

### Actual behaviour
Errors

## System Configuration

 

- LBRY Daemon version:
- LBRY App version: 0.11.3
- LBRY Installation ID:
- Operating system:

## Anything Else

2017-06-01 00:48:30,025 ERROR    lbrynet.lbrynet_daemon.auth.server:346: Failed to process file_list: 'ascii' codec can't decode byte 0xe2 in position 10: ordinal not in range(128)
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
  File "site-packages\lbrynet\lbrynet_daemon\Daemon.py", line 863, in _get_lbry_file_dict
  File "ntpath.py", line 85, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10: ordinal not in range(128)
2017-06-01 00:48:30,029 ERROR    lbrynet.lbrynet_daemon.auth.server:346: Failed to process file_list: 'ascii' codec can't decode byte 0xe2 in position 10: ordinal not in range(128)
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
  File "site-packages\lbrynet\lbrynet_daemon\Daemon.py", line 863, in _get_lbry_file_dict
  File "ntpath.py", line 85, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10: ordinal not in range(128)
2017-06-01 00:48:30,046 INFO     lbrynet.lbrynet_daemon.Daemon:2534: Already have sd blob
2017-06-01 00:48:30,046 INFO     lbrynet.lbrynet_daemon.Daemon:2552: check peers for 5 of 9 blobs in stream
2017-06-01 00:48:44,476 ERROR    lbrynet.lbrynet_daemon.auth.server:346: Failed to process file_list: 'ascii' codec can't decode byte 0xe2 in position 10: ordinal not in range(128)
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
  File "site-packages\lbrynet\lbrynet_daemon\Daemon.py", line 863, in _get_lbry_file_dict
  File "ntpath.py", line 85, in join

**Comment by tzarebczan** [comment]
Same as #177

**Comment by lyoshenka** [comment]
@tzarebczan i don't think this is the same issue. I'm gonna leave this open.

**Comment by tzarebczan** [comment]
Thanks, I looked at yours too quickly and jumped the gun.

**Comment by mikesimps** [comment]
I had the same issue, but the video downloaded fine (I could open the file), it just wouldn't play back in the app. Restarted the app, but same problem exists. Screenshot of file name on my smb share.

daemon (lbrynet)	0.10.3
wallet (lbryum)	2.7.22
interface	0.11.9
Platform	Windows (Windows-10-10.0.15063)
Installation ID	8HbA7w4ymREsjcJETCceqL3zyc5GGBUs7ru1EZDDdCsJmzQYsopRfSjH95isnUtQyV

![image](https://cloud.githubusercontent.com/assets/3085186/26697640/b507df80-46e0-11e7-9f4d-93039039f04b.png)

**Comment by kauffj** [comment]
This is a bug in `lbry` open for this.
