### ISSUE TITLE
Invalid char in channel name causes app to throw error

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#177]
Reilly typoed a featured channel, adding an extra comma at the end. This broke the homepage completely. App should do a better job recovering from this.

Channel `overwatch-horizon-trailer,`

Error:

```
Uncaught (in promise) Error: Invalid character in name: ,.
    at Object.lbryuri.parse (file:///Applications/LBRY.app/Contents/Resources/app/dist/js/bundle.js:31453:12)
    at Object.lbryuri.normalize (file:///Applications/LBRY.app/Contents/Resources/app/dist/js/bundle.js:31550:33)
    at file:///Applications/LBRY.app/Contents/Resources/app/dist/js/bundle.js:53301:123
    at Array.map (native)
    at FeaturedCategory (file:///Applications/LBRY.app/Contents/Resources/app/dist/js/bundle.js:53300:21)
    at file:///Applications/LBRY.app/Contents/Resources/app/dist/js/bundle.js:24153:17
    at measureLifeCyclePerf (file:///Applications/LBRY.app/Contents/Resources/app/dist/js/bundle.js:23922:13)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (file:///Applications/LBRY.app/Contents/Resources/app/dist/js/bundle.js:24152:15)
    at ReactCompositeComponentWrapper._constructComponent (file:///Applications/LBRY.app/Contents/Resources/app/dist/js/bundle.js:24127:22)
    at ReactCompositeComponentWrapper.mountComponent (file:///Applications/LBRY.app/Contents/Resources/app/dist/js/bundle.js:24035:22)
```

**Comment by tzarebczan** [comment]
Looks like the same as this issue I reported last night https://github.com/lbryio/lbry-app/issues/174 Will close it.

**Comment by btzr-io** [comment]
I can't recreate this in `15.0.0`
@tzarebczan I think this was also fixed ?

**Comment by btzr-io** [comment]
https://github.com/lbryio/lbry-app/blob/master/ui/js/lbryuri.js#L6

**Comment by tzarebczan** [comment]
Thanks @btzr-io , will close.
