### ISSUE TITLE
Javascript error when opening a lbry:// link

### ISSUE THREAD

**Issue by oakey22** [lbryio/lbry-app#197]
## The Issue
When clicking a lbry://music link the app loads up and then displays the error 
A javascript error occured in the main process. You can see the screen in the snapshot
[https://spee.ch/error101](https://spee.ch/error101)
The link does not load in the app after this.

### Steps to reproduce
1.Open Lbry
2. Click on any lbry://link outside of the app

### Expected behaviour
Should load the link in the lbry app

### Actual behaviour
Gives a javascript error

## System Configuration

 

```
daemon (lbrynet)	0.11.0rc1
wallet (lbryum)	2.7.24
interface	0.11.9
Platform	Linux (Linux-4.4.0-78-generic-x86_64-with-Ubuntu-16.04-xenial)
Installation ID	8GSRXZNbr5xCkQG3dy4rXXXDNcUHk36tQTuZsAYTaV8TFqqTZfocF5jbN1doodh1Yq
```

```
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "rc",
    "ip": "86.149.170.54",
    "lbrynet_version": "0.11.0rc1",
    "lbryschema_version": "0.0.6",
    "lbryum_version": "2.7.24",
    "os_release": "4.4.0-78-generic",
    "os_system": "Linux",
    "platform": "Linux-4.4.0-78-generic-x86_64-with-Ubuntu-16.04-xenial",
    "processor": "x86_64",
    "python_version": "2.7.12"
  }
}
```

**Comment by nikooo777** [comment]
i confirm getting this as well the other day:

```
Uncaught Exception:
Error: EBADF: bad file descriptor, write
    at Object.fs.writeSync (fs.js:719:20)
    at SyncWriteStream._write (internal/fs.js:75:6)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SyncWriteStream.Writable.write (_stream_writable.js:245:11)
    at Console.log (console.js:43:16)
    at launchDaemonIfNotRunning (/opt/LBRY/resources/app/main.js:239:11)
    at App.<anonymous> (/opt/LBRY/resources/app/main.js:232:3)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```

it resolved after a restart of my pc

**Comment by kauffj** [comment]
Please re-open if happening in 0.12.x or later.
