### ISSUE TITLE
all cards say me "this address containts no content"

### ISSUE THREAD

**Issue by setar** [lbryio/lbry-app#243]
## The Issue
all cards say me "this address containts no content"

### Steps to reproduce
1. run lbry-app

### Expected behaviour
any content :)

### Actual behaviour
no content

## System Configuration
{
  "build": "rc",
  "lbrynet_version": "0.12.2rc2",
  "lbryschema_version": "0.0.7",
  "lbryum_version": "2.8.1",
  "os_release": "10",
  "os_system": "Windows",
  "platform": "Windows-10-10.0.14393",
  "processor": "Intel64 Family 6 Model 94 Stepping 3, GenuineIntel",
  "python_version": "2.7.13"
}

- LBRY Daemon version: v0.13.1rc1
- LBRY App version: v0.12.0
- LBRY Installation ID: 
- Operating system: win10

## Anything Else
debug from daemon containt errors:

```
PS C:\Users\setar\Downloads\lbrynet-daemon-v0.13.1rc1-windows> .\lbrynet-daemon.exe --verbose
2017-06-15 22:50:48,509 DEBUG    lbrynet.lbrynet_daemon.DaemonControl:82: Final Settings: {'download_directory': 'C:\\Users\\setar\\Downloads\\LBRY', 'CURRENCIES': {'L
BC': {'type': 'crypto'}, 'USD': {'type': 'fiat'}, 'BTC': {'type': 'crypto'}}, 'data_rate': 0.0001, 'delete_blobs_on_remove': True, 'CRYPTSD_FILE_EXTENSION': '.cryptsd'
, 'BLOBFILES_DIR': 'blobfiles', 'host_ui': True, 'last_version': {'lbryum': '0.0.1', 'lbrynet': '0.0.1'}, 'WALLET_TYPES': ['lbryum', 'lbrycrd'], 'api_port': 5279, 'ANA
LYTICS_ENDPOINT': 'https://api.segment.io/v1', 'PROTOCOL_PREFIX': 'lbry', 'check_ui_requirements': True, 'use_upnp': True, 'min_info_rate': 0.02, 'cache_time': 150, 'L
OGGLY_TOKEN': 'LJEzATH4AzRgAwxjAP00LwZ2YGx3MwVgZTMuBQZ3MQuxLmOv', 'max_upload': 0.0, 'max_search_results': 25, 'MAX_BLOB_INFOS_TO_REQUEST': 20, 'max_download': 0.0, 'S
OURCE_TYPES': ['lbry_sd_hash', 'url', 'btih'], 'MAX_RESPONSE_INFO_SIZE': 65536, 'pointtrader_server': 'http://127.0.0.1:2424', 'reflect_uploads': True, 'use_auth_http'
: False, 'MAX_BLOB_REQUEST_SIZE': 65536, 'share_usage_data': True, 'ANALYTICS_TOKEN': 'Ax5LZzR1o3q3Z3WjATASDwR5rKyHH0qOIRIbLmMXn2H=', 'local_ui_path': '', 'ui_branch':
 'master', 'max_key_fee': {'currency': 'USD', 'amount': 25.0, 'address': ''}, 'search_timeout': 5.0, 'allowed_origin': '', 'MAX_REQUEST_SIZE': 65536, 'ICON_PATH': 'ico
ns', 'run_on_startup': False, 'startup_scripts': [], 'download_timeout': 180, 'max_connections_per_stream': 5, 'BLOB_SIZE': 2097152, 'SLACK_WEBHOOK': 'nUE0pUZ6Yl9bo29e
pl5moTSwnl5wo20ip2IlqzywMKZiIQSFZR5AHx4mY0VmF0WQZ1ESEP9kMHZlp1WzJwWOoKN3ImR1M2yUAaMyqGZ=', 'dht_node_port': 4444, 'data_dir': u'C:\\Users\\setar\\AppData\\Roaming\\lbr
ynet', 'peer_port': 3333, 'reflector_port': 5566, 'APP_NAME': 'LBRY', 'run_reflector_server': False, 'DB_REVISION_FILE_NAME': 'db_revision', 'sd_download_timeout': 3,
'reflector_servers': [('reflector.lbry.io', 5566)], 'api_host': 'localhost', 'min_valuable_hash_rate': 0.05, 'is_generous_host': True, 'lbryum_wallet_dir': u'C:\\Users
\\setar\\AppData\\Roaming\\lbryum', 'default_ui_branch': 'master', 'wallet': 'lbryum', 'API_ADDRESS': 'lbryapi', 'search_servers': ['lighthouse1.lbry.io:50005'], 'LOG_
POST_URL': 'https://lbry.io/log-upload', 'peer_search_timeout': 3, 'known_dht_nodes': [('lbrynet1.lbry.io', 4444), ('lbrynet2.lbry.io', 4444), ('lbrynet3.lbry.io', 444
4)], 'min_valuable_info_rate': 0.05, 'LOG_FILE_NAME': 'lbrynet.log', 'MAX_HANDSHAKE_SIZE': 65536}
2017-06-15 22:50:48,510 DEBUG    lbrynet.lbrynet_daemon.DaemonControl:85: Checking for an existing lbrynet daemon instance
2017-06-15 22:50:50,516 DEBUG    lbrynet.lbrynet_daemon.DaemonControl:90: No lbrynet instance found, continuing to start
2017-06-15 22:50:50,516 INFO     lbrynet.lbrynet_daemon.DaemonControl:92: Starting lbrynet-daemon from command line
2017-06-15 22:50:50,517 DEBUG    lbrynet.core.utils:93: Checking connection to lbry.io:80
2017-06-15 22:50:50,703 DEBUG    lbrynet.core.utils:96: Connection successful
2017-06-15 22:50:52,624 DEBUG    lbrynet.analytics:241: Sending track event: {'timestamp': '2017-06-15T19:50:52.624000Z', 'userId': 'lbry', 'event': 'Server Startup',
'context': {'app': {'build': 'rc', 'version': '0.13.1rc1', 'name': 'lbrynet', 'wallet': {'version': '2.8.2', 'name': 'lbryum'}, 'python_version': '2.7.13'}, 'os': {'ve
rsion': '10', 'name': 'Windows'}, 'library': {'version': '1.0.0', 'name': 'lbrynet-analytics'}}, 'properties': {'lbry_id': 'A9aUMLL9tYyammGHc1n6tkm3uY1zTpqJLe8hMqB8gRQ
n7KaLeFgCorJ4Jz75o2p2do', 'session_id': '6QoL2aaogPumYzfecuqV9fBjX1eojf81HUxBYsFPGnMyVdVxxhrFHG5ZQuS6fXEQ9L'}}
2017-06-15 22:50:52,631 INFO     lbrynet.lbrynet_daemon.DaemonServer:64: Using non-authenticated API
2017-06-15 22:50:52,642 INFO     lbrynet.lbrynet_daemon.Daemon:254: Starting lbrynet-daemon
2017-06-15 22:50:52,644 DEBUG    lbrynet.core.utils:93: Checking connection to lbry.io:80
2017-06-15 22:50:52,826 DEBUG    lbrynet.core.utils:96: Connection successful
2017-06-15 22:50:52,826 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:174: Starting exchange rate manager
2017-06-15 22:50:54,032 INFO     lbrynet.lbrynet_daemon.Daemon:281: Platform: {"lbrynet_version": "0.13.1rc1", "platform": "Windows-10-10.0.14393", "os_system": "Windo
ws", "python_version": "2.7.13", "os_release": "10", "lbryum_version": "2.8.2", "ip": "91.122.37.85", "lbryschema_version": "0.0.7", "processor": "Intel64 Family 6 Mod
el 94 Stepping 3, GenuineIntel", "build": "rc"}
2017-06-15 22:50:54,046 INFO     lbrynet.lbrynet_daemon.Daemon:488: Loading databases
2017-06-15 22:50:54,059 INFO     lbrynet.lbrynet_daemon.Daemon:558: Using lbryum wallet
2017-06-15 22:50:54,066 DEBUG    lbrynet.core.Session:143: Setting up the lbry session
2017-06-15 22:50:54,068 DEBUG    lbrynet.core.Session:194: In _try_upnp
2017-06-15 22:50:54,071 WARNING  lbrynet.lbrynet_daemon.auth.server:335: Function not allowed during startup wallet_balance: wallet_balance
2017-06-15 22:50:54,138 DEBUG    lbrynet.lbrynet_daemon.ExchangeRateManager:63: Saving price update 0.000400 for USDBTC
2017-06-15 22:50:54,720 DEBUG    lbrynet.lbrynet_daemon.ExchangeRateManager:63: Saving price update 3841.687709 for BTCLBC
2017-06-15 22:50:56,736 WARNING  lbrynet.lbrynet_daemon.auth.server:335: Function not allowed during startup wallet_balance: wallet_balance
2017-06-15 22:50:58,079 INFO     lbrynet.core.Session:254: Starting DHT
2017-06-15 22:50:58,246 INFO     lbrynet.dht.protocol:216: DHT listening on UDP 4444
2017-06-15 22:50:58,247 DEBUG    lbrynet.dht.protocol:202: DHT SEND CALL findNode(b7fc6d33460a9914e3c1da60b881f76ba1690dcf452f87995690ff368fdb8eb4c05ece7eb3660e193b698
62ca76a5a27)
2017-06-15 22:50:58,249 DEBUG    lbrynet.dht.protocol:202: DHT SEND CALL findNode(b7fc6d33460a9914e3c1da60b881f76ba1690dcf452f87995690ff368fdb8eb4c05ece7eb3660e193b698
62ca76a5a27)
2017-06-15 22:50:58,250 DEBUG    lbrynet.dht.protocol:202: DHT SEND CALL findNode(b7fc6d33460a9914e3c1da60b881f76ba1690dcf452f87995690ff368fdb8eb4c05ece7eb3660e193b698
62ca76a5a27)
2017-06-15 22:50:58,250 DEBUG    lbrynet.core.server.DHTHashAnnouncer:49: Announcing available hashes
2017-06-15 22:50:58,252 DEBUG    lbrynet.core.Session:290: Setting up the rest of the components
2017-06-15 22:50:58,259 INFO     lbrynet.core.RateLimiter:72: Starting <lbrynet.core.RateLimiter.RateLimiter object at 0x047FAE50>
2017-06-15 22:50:58,260 INFO     lbrynet.core.BlobManager:97: Setting up the DiskBlobManager. blob_dir: C:\Users\setar\AppData\Roaming\lbrynet\blobfiles, db_file: C:\U
sers\setar\AppData\Roaming\lbrynet\blobs.db
2017-06-15 22:50:58,457 INFO     lbryum.network:35: lbryum7.lbry.io:50001 is online
2017-06-15 22:50:58,654 INFO     lbryum.network:35: lbryum6.lbry.io:50001 is online
2017-06-15 22:50:58,655 INFO     lbryum.network:363: starting network
2017-06-15 22:50:58,657 INFO     lbryum.network:331: connecting to lbryum7.lbry.io:50001:t as new interface
2017-06-15 22:50:58,660 INFO     lbrynet.core.Wallet:1143: Loading the wallet
2017-06-15 22:50:58,661 INFO     lbryum.network:750: Initializing the blockchain
2017-06-15 22:50:58,663 INFO     lbryum:44: wallet path C:\Users\setar\AppData\Roaming\lbryum\wallets\default_wallet
2017-06-15 22:50:58,664 INFO     lbryum:44: 191704 blocks
2017-06-15 22:50:58,667 INFO     lbryum.network:752: Blockchain initialized, starting run loop
2017-06-15 22:50:58,788 INFO     lbryum:44: connected
2017-06-15 22:50:58,803 INFO     lbryum:44: connected
2017-06-15 22:50:58,871 INFO     lbryum.network:428: switching to lbryum7.lbry.io:50001:t
2017-06-15 22:50:58,872 INFO     lbryum.network:269: sending subscriptions to lbryum7.lbry.io:50001:t. Unanswered requests: 0, Subscribed addresses: 0
2017-06-15 22:50:59,173 INFO     lbrynet.core.Wallet:1234: Local Height: 191704, remote height: 191704, behind: 0
2017-06-15 22:50:59,174 INFO     lbrynet.core.Wallet:1242: Wallet Loaded
2017-06-15 22:50:59,176 INFO     lbrynet.core.Wallet:1167: Subscribing to addresses
2017-06-15 22:50:59,355 INFO     lbryum.network:473: relayfee 1000
2017-06-15 22:50:59,355 INFO     lbryum.network:468: recommended fee -100000000
2017-06-15 22:51:00,615 INFO     lbryum:44: connected at height: 191704
2017-06-15 22:51:00,681 INFO     lbrynet.core.Wallet:1169: Synchronized wallet
2017-06-15 22:51:00,681 DEBUG    lbrynet.core.Wallet:522: Got a new balance: 2.97675581
2017-06-15 22:51:00,683 INFO     lbrynet.core.BlobAvailability:30: Starting <lbrynet.core.BlobAvailability.BlobAvailabilityTracker object at 0x047FA7D0>
2017-06-15 22:51:00,683 DEBUG    lbrynet.core.BlobAvailability:93: ==> Updating the peers for my blobs
2017-06-15 22:51:00,684 DEBUG    lbrynet.analytics:241: Sending track event: {'timestamp': '2017-06-15T19:51:00.684000Z', 'userId': 'lbry', 'event': 'Heartbeat', 'cont
ext': {'app': {'build': 'rc', 'version': '0.13.1rc1', 'name': 'lbrynet', 'wallet': {'version': '2.8.2', 'name': 'lbryum'}, 'python_version': '2.7.13'}, 'os': {'version
': '10', 'name': 'Windows'}, 'library': {'version': '1.0.0', 'name': 'lbrynet-analytics'}}, 'properties': {'lbry_id': 'A9aUMLL9tYyammGHc1n6tkm3uY1zTpqJLe8hMqB8gRQn7KaL
eFgCorJ4Jz75o2p2do', 'session_id': '6QoL2aaogPumYzfecuqV9fBjX1eojf81HUxBYsFPGnMyVdVxxhrFHG5ZQuS6fXEQ9L'}}
2017-06-15 22:51:00,684 INFO     lbrynet.lbrynet_daemon.Daemon:531: Starting to setup up file manager
2017-06-15 22:51:00,687 DEBUG    lbrynet.core.BlobManager:123: Making a new blob for 12faf6557cdceecbcf688ed6c0c63ab464f3dad2b738205e611e255b4b98f4a5f71e7d9d4bca0fd8f4
ce5e2b6a71d833
2017-06-15 22:51:00,687 DEBUG    lbrynet.core.BlobManager:123: Making a new blob for 3bfcc15fed5cc1f72192ed818c1530385d1053c8519c6b32dac0d9fd1a5b3a6f7b0623398acb377822
1dc1ede4c2ec7b
2017-06-15 22:51:00,687 DEBUG    lbrynet.core.BlobManager:123: Making a new blob for 66c3d6bfb9a3a4a86b5aa79c7cad180172779df5c921e41cf8461686943fb5da3f498c7d7028c50541
5991f2f1146fdd
2017-06-15 22:51:00,688 DEBUG    lbrynet.core.BlobManager:123: Making a new blob for 8d958bb6b8bf2f9805b5e41a028f704dfcd4b17491de5a05cfc32ace45aab7bc91bc7e1a692bdac6a3
d7b4c9d03f3b87
2017-06-15 22:51:00,688 DEBUG    lbrynet.core.BlobManager:123: Making a new blob for a8655e8b2d6cdadf48274a9484e8cbc721a9460d7781dfd02a87c06cf40c70e67e751109353c7fd52d
e9b6bab557728f
2017-06-15 22:51:00,690 DEBUG    lbrynet.core.BlobAvailability:103: <== Done updating peers for my blobs. Took 0.00699996948242 seconds
2017-06-15 22:51:00,690 DEBUG    lbrynet.analytics:241: Sending track event: {'timestamp': '2017-06-15T19:51:00.691000Z', 'userId': 'lbry', 'event': 'Blob Bytes Availa
ble', 'context': {'app': {'build': 'rc', 'version': '0.13.1rc1', 'name': 'lbrynet', 'wallet': {'version': '2.8.2', 'name': 'lbryum'}, 'python_version': '2.7.13'}, 'os'
: {'version': '10', 'name': 'Windows'}, 'library': {'version': '1.0.0', 'name': 'lbrynet-analytics'}}, 'properties': {'lbry_id': 'A9aUMLL9tYyammGHc1n6tkm3uY1zTpqJLe8hM
qB8gRQn7KaLeFgCorJ4Jz75o2p2do', 'value': 7745550L, 'session_id': '6QoL2aaogPumYzfecuqV9fBjX1eojf81HUxBYsFPGnMyVdVxxhrFHG5ZQuS6fXEQ9L'}}
2017-06-15 22:51:00,693 DEBUG    lbrynet.lbryfilemanager.EncryptedFileManager:54: Download directory for EncryptedFileManager: C:\Users\setar\Downloads\LBRY
2017-06-15 22:51:00,697 DEBUG    lbrynet.lbryfilemanager.EncryptedFileManager:115: Checking 1 streams
2017-06-15 22:51:00,698 DEBUG    lbrynet.lbryfile.EncryptedFileMetadataManager:251: Looking up sd blob hashes for stream hash 81b163dafe4062a2a9ecd5be6a2bfcc8b0c89a1fb
d188a38e7fd3842240527aeadd73137da93ccd660cccacb7961a2a7
2017-06-15 22:51:00,703 INFO     lbrynet.lbryfilemanager.EncryptedFileDownloader:32: lbry://roboforum (a8655e) is finished
2017-06-15 22:51:00,703 INFO     lbrynet.lbryfilemanager.EncryptedFileManager:126: Started 1 lbry files
2017-06-15 22:51:00,703 INFO     lbrynet.lbrynet_daemon.Daemon:542: Done setting up file manager
2017-06-15 22:51:00,746 INFO     lbrynet.lbrynet_daemon.Daemon:271: Starting balance: 2.97675581
2017-06-15 22:51:00,747 DEBUG    lbrynet.reflector.client.client:352: Starting reflector factory
2017-06-15 22:51:00,749 DEBUG    lbrynet.reflector.client.client:356: Connecting to reflector
2017-06-15 22:51:00,750 INFO     lbrynet.lbrynet_daemon.Daemon:248: Started lbrynet-daemon
2017-06-15 22:51:00,750 INFO     lbrynet.lbrynet_daemon.Daemon:249: 5 blobs in manager
2017-06-15 22:51:00,750 DEBUG    lbrynet.analytics:241: Sending track event: {'timestamp': '2017-06-15T19:51:00.751000Z', 'userId': 'lbry', 'event': 'Server Startup Su
ccess', 'context': {'app': {'build': 'rc', 'version': '0.13.1rc1', 'name': 'lbrynet', 'wallet': {'version': '2.8.2', 'name': 'lbryum'}, 'python_version': '2.7.13'}, 'o
s': {'version': '10', 'name': 'Windows'}, 'library': {'version': '1.0.0', 'name': 'lbrynet-analytics'}}, 'properties': {'lbry_id': 'A9aUMLL9tYyammGHc1n6tkm3uY1zTpqJLe8
hMqB8gRQn7KaLeFgCorJ4Jz75o2p2do', 'session_id': '6QoL2aaogPumYzfecuqV9fBjX1eojf81HUxBYsFPGnMyVdVxxhrFHG5ZQuS6fXEQ9L'}}
2017-06-15 22:51:00,826 INFO     lbryum:44: connected at height: 191704
2017-06-15 22:51:01,740 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:51:06,740 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.001000
2017-06-15 22:51:11,736 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.001000
2017-06-15 22:51:16,740 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:51:21,739 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:51:21,750 ERROR    lbrynet.reflector.client.client:365: Reflector connection failed: [Failure instance: Traceback (failure with no frames): <class 'twist
ed.internet.error.TCPTimedOutError'>: TCP connection timed out: 10060: ╧юя√Єър єёЄрэютшЄ№ ёюхфшэхэшх с√ыр схчєёях°эющ, Є.ъ. юЄ фЁєуюую ъюья№■ЄхЁр чр ЄЁхсєхьюх тЁхь  эх
 яюыєўхэ эєцэ√щ юЄъышъ, шыш с√ыю ЁрчюЁтрэю єцх єёЄрэютыхээюх ёюхфшэхэшх шч-чр эхтхЁэюую юЄъышър єцх яюфъы■ўхээюую ъюья№■ЄхЁр..
]
Traceback (most recent call last):
  File "site-packages\lbrynet\core\log_support.py", line 57, in emit
  File "logging\__init__.py", line 734, in format
  File "site-packages\lbrynet\core\log_support.py", line 180, in format
  File "json\__init__.py", line 244, in dumps
  File "json\encoder.py", line 207, in encode
  File "json\encoder.py", line 270, in iterencode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xcf in position 168: invalid continuation byte
Logged from file client.py, line 365
2017-06-15 22:51:26,739 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:51:31,739 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:51:36,739 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:51:41,740 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:51:46,739 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:51:51,736 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.001000
2017-06-15 22:51:56,737 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.001000
2017-06-15 22:51:57,704 DEBUG    lbrynet.core.Wallet:645: There were no payments to send
2017-06-15 22:51:58,252 DEBUG    lbrynet.core.server.DHTHashAnnouncer:49: Announcing available hashes
2017-06-15 22:51:58,255 DEBUG    lbrynet.core.BlobManager:296: Got 0 blobs to announce, next announce time is in 3599.99899983 seconds
2017-06-15 22:51:58,339 INFO     lbryum.network:616: network: retrying connections
2017-06-15 22:52:00,684 DEBUG    lbrynet.analytics:241: Sending track event: {'timestamp': '2017-06-15T19:52:00.684000Z', 'userId': 'lbry', 'event': 'Heartbeat', 'cont
ext': {'app': {'build': 'rc', 'version': '0.13.1rc1', 'name': 'lbrynet', 'wallet': {'version': '2.8.2', 'name': 'lbryum'}, 'python_version': '2.7.13'}, 'os': {'version
': '10', 'name': 'Windows'}, 'library': {'version': '1.0.0', 'name': 'lbrynet-analytics'}}, 'properties': {'lbry_id': 'A9aUMLL9tYyammGHc1n6tkm3uY1zTpqJLe8hMqB8gRQn7KaL
eFgCorJ4Jz75o2p2do', 'session_id': '6QoL2aaogPumYzfecuqV9fBjX1eojf81HUxBYsFPGnMyVdVxxhrFHG5ZQuS6fXEQ9L'}}
2017-06-15 22:52:01,740 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:52:06,740 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.001000
2017-06-15 22:52:11,740 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:52:16,739 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:52:21,739 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:52:26,740 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:52:31,739 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:52:36,739 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:52:41,739 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:52:46,739 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:52:51,737 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.001000
2017-06-15 22:52:56,736 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.001000
2017-06-15 22:52:57,729 DEBUG    lbrynet.core.Wallet:645: There were no payments to send
2017-06-15 22:52:58,253 DEBUG    lbrynet.core.server.DHTHashAnnouncer:49: Announcing available hashes
2017-06-15 22:52:58,255 DEBUG    lbrynet.core.BlobManager:296: Got 0 blobs to announce, next announce time is in 3599.99899983 seconds
2017-06-15 22:52:58,388 INFO     lbryum.network:616: network: retrying connections
2017-06-15 22:53:00,684 DEBUG    lbrynet.analytics:241: Sending track event: {'timestamp': '2017-06-15T19:53:00.684000Z', 'userId': 'lbry', 'event': 'Heartbeat', 'cont
ext': {'app': {'build': 'rc', 'version': '0.13.1rc1', 'name': 'lbrynet', 'wallet': {'version': '2.8.2', 'name': 'lbryum'}, 'python_version': '2.7.13'}, 'os': {'version
': '10', 'name': 'Windows'}, 'library': {'version': '1.0.0', 'name': 'lbrynet-analytics'}}, 'properties': {'lbry_id': 'A9aUMLL9tYyammGHc1n6tkm3uY1zTpqJLe8hMqB8gRQn7KaL
eFgCorJ4Jz75o2p2do', 'session_id': '6QoL2aaogPumYzfecuqV9fBjX1eojf81HUxBYsFPGnMyVdVxxhrFHG5ZQuS6fXEQ9L'}}
2017-06-15 22:53:01,740 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.001000
2017-06-15 22:53:06,740 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.003000
2017-06-15 22:53:11,739 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:53:16,740 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:53:21,739 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:53:26,739 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000
2017-06-15 22:53:31,740 DEBUG    lbrynet.lbrynet_daemon.auth.server:415: wallet_balance took 0.002000


```

**Comment by tzarebczan** [comment]
Don't click enter after your search, that takes you to the claim.

**Comment by setar** [comment]
i just open lbry-app, and do not click any button ...
![1](https://user-images.githubusercontent.com/1164389/27200285-e4bf129c-5221-11e7-9f13-24c62716ea56.JPG)

**Comment by tzarebczan** [comment]
Did it ever work correctly? Have you tried restarting? Try reinstalling also.

**Comment by setar** [comment]
try paste in URL string any link from #content channel
![2](https://user-images.githubusercontent.com/1164389/27200659-53c202b6-5223-11e7-85f4-57c162785560.JPG)

**Comment by tzarebczan** [comment]
Looks like something is blocked on your end. Check firewall?

**Comment by setar** [comment]
sorry, my bag :)
I ran the daemon separately, in the next window
But it is already embedded ...
