### ISSUE TITLE
Cannot stream lbry://bellflower or coherenace in app - console errors

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#418]
## The Issue
Whern trying to stream lbry://bellflower#f01cf8a0b58b194cd7947885c5dc1028a9296d1c (costs ~10LBC), it gets stuck at 0:00 and console throws errors. Issue with Video file or our streaming capability? 
### Steps to reproduce
1. stream lbry://bellflower#f01cf8a0b58b194cd7947885c5dc1028a9296d1c 
2. check console, see error below

### Expected behaviour
Should stream in app
### Actual behaviour
Does not stream

## System Configuration

 

- LBRY Daemon version: 0.14.2
- LBRY App version: 0.14
- LBRY Installation ID:
- Operating system: Windows

## Anything Else

```
16:16:33.584 buffer.js:1049 Uncaught TypeError: "value" argument is out of bounds
    at checkInt (buffer.js:1049:11)
    at Buffer.writeUInt32BE (buffer.js:1142:5)
    at exports.trun.encode (file:///C:/Program%20Files%20(x86)/LBRY/resources/app/dist/js/bundle.js:66653:9)
    at Object.Box._encode (file:///C:/Program%20Files%20(x86)/LBRY/resources/app/dist/js/bundle.js:11041:5)
    at file:///C:/Program%20Files%20(x86)/LBRY/resources/app/dist/js/bundle.js:11029:13
    at Array.forEach (native)
    at Object.Box._encode (file:///C:/Program%20Files%20(x86)/LBRY/resources/app/dist/js/bundle.js:11020:14)
    at file:///C:/Program%20Files%20(x86)/LBRY/resources/app/dist/js/bundle.js:11025:15
    at Array.forEach (native)
    at file:///C:/Program%20Files%20(x86)/LBRY/resources/app/dist/js/bundle.js:11024:15
checkInt @ buffer.js:1049
Buffer.writeUInt32BE @ buffer.js:1142
exports.trun.encode @ boxes.js:840
Box._encode @ index.js:76
(anonymous) @ index.js:64
Box._encode @ index.js:55
(anonymous) @ index.js:60
(anonymous) @ index.js:59
Box._encode @ index.js:55
Box.encode @ index.js:31
Encoder.box @ encode.js:62
writeFragment @ mp4-remuxer.js:318
(anonymous) @ mp4-remuxer.js:314
MP4Remuxer.seek @ mp4-remuxer.js:294
VideoStream._pump @ videostream.js:78
VideoStream.self._onWaiting @ videostream.js:34
16:16:33.585 mp4-remuxer.js:321 Uncaught TypeError: Cannot read property 'slice' of undefined
    at file:///C:/Program%20Files%20(x86)/LBRY/resources/app/dist/js/bundle.js:120428:38
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by tzarebczan** [comment]
Same happens for lbry://coherence#7cae78226d2b6f972c10c24e1ce9f40f71883bd0

**Comment by kauffj** [comment]
I'm pretty clueless on this one. When testing on Linux, it also did not work, but the daemon responded "float argument required, not NoneType".

**Comment by kauffj** [comment]
@jackrobison do these stream for you?

**Comment by tzarebczan** [comment]
@kauffj any reason for closing this? I think it needs to be looked at, especially since these videos are on our front page.

**Comment by kauffj** [comment]
How widespread / common is this? Are there any other reports? Is it just this movie? I've never been able to reproduce this.

**Comment by tzarebczan** [comment]
@kauffj I'm not sure what other videos it's happening to besides coherence and bellflower, but since these are on our homepage, they ought to work. 

I thought you said you said "it did not work" for you [here](https://github.com/lbryio/lbry-app/issues/418#issuecomment-320961838), unless you meant you weren't able to reproduce it.

**Comment by seanyesmunt** [comment]
@tzarebczan 

"I just tried republishing the same raw file and it produces the same result"

Not sure if I follow; does that mean the issues is with the actual file?

**Comment by tzarebczan** [comment]
Yep, something to do with the file encoding possibly.
