### ISSUE TITLE
Internal Error when trying to Publish without an insufficient balance

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#427]
## The Issue
When trying to create a channel for more LBC than exists in your wallet, you get an internal error as opposed to a better insufficient funds message.  We should also make a note of TX and Publish fees, because if someone has 10 LBC, they most likely won't be able to claim for 10. 

Log shows:
```shell
2017-08-03 08:23:38,674 ERROR    lbrynet.daemon.auth.server:353: Failed to process channel_new: Invalid amount
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
  File "site-packages\lbrynet\daemon\Daemon.py", line 1663, in jsonrpc_channel_new
Exception: Invalid amount
2017-08-03 08:24:45,992 ERROR    lbrynet.daemon.auth.server:353: Failed to process channel_new: 
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
  File "site-packages\lbrynet\daemon\Daemon.py", line 1665, in jsonrpc_channel_new
InsufficientFundsError
```

### Steps to reproduce
1. Publish something for more LBC than you have in your wallet
2. See internal error
![internal error](https://user-images.githubusercontent.com/8120721/28929666-94609080-783e-11e7-8f35-39b954e5e3d8.JPG)
3.

### Expected behaviour
Should be told insufficient funds

### Actual behaviour
Internal error

## System Configuration

 

- LBRY Daemon version: 0.14.2
- LBRY App version:0.14.3rc2
- LBRY Installation ID:
- Operating system: Win 10

**Comment by kauffj** [comment]
@tzarebczan any time the daemon throws an exception rather than cleanly returning a signature that indicates an error, it's a bug in the daemon.

**Comment by tzarebczan** [comment]
Sorry, just saw this now - reopening on the lbry side.

**Comment by tzarebczan** [comment]
Issue moved to [lbryio/lbry #855](https://github.com/lbryio/lbry/issues/855) via [**ZenHub**](https://www.zenhub.com/)
