### ISSUE TITLE
Lbry unresponsive when clicking menu buttons

### ISSUE THREAD

**Issue by oakey22** [lbryio/lbry-app#548]
### Steps to reproduce
1.Click settings, click home, click settings, click publish, click home, click settings, etc

### Expected behaviour
Should go to each screen when clicked

### Actual behaviour
The app becomes unresponsive when clicked so many times other than the name changing in the search bar and title bar
### Fault in developer tools

`Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
    at file:///opt/LBRY/resources/app/dist/js/bundle.js:35181:26
    at Array.map (native)
    at ChannelSection.render (file:///opt/LBRY/resources/app/dist/js/bundle.js:35180:29)
    at file:///opt/LBRY/resources/app/dist/js/bundle.js:74359:21
    at measureLifeCyclePerf (file:///opt/LBRY/resources/app/dist/js/bundle.js:73639:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (file:///opt/LBRY/resources/app/dist/js/bundle.js:74358:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:74385:32)
    at ReactCompositeComponentWrapper._updateRenderedComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:74309:36)
    at ReactCompositeComponentWrapper._performComponentUpdate (file:///opt/LBRY/resources/app/dist/js/bundle.js:74287:10)
    at ReactCompositeComponentWrapper.updateComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:74208:12)
bundle.js:35181 Uncaught TypeError: Cannot read property 'name' of undefined
    at file:///opt/LBRY/resources/app/dist/js/bundle.js:35181:26
    at Array.map (native)
    at ChannelSection.render (file:///opt/LBRY/resources/app/dist/js/bundle.js:35180:29)
    at file:///opt/LBRY/resources/app/dist/js/bundle.js:74359:21
    at measureLifeCyclePerf (file:///opt/LBRY/resources/app/dist/js/bundle.js:73639:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (file:///opt/LBRY/resources/app/dist/js/bundle.js:74358:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:74385:32)
    at ReactCompositeComponentWrapper.performInitialMount (file:///opt/LBRY/resources/app/dist/js/bundle.js:73925:30)
    at ReactCompositeComponentWrapper.mountComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:73821:21)
    at Object.mountComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:7994:35)
bundle.js:9341 Uncaught TypeError: Cannot read property 'replaceChild' of null
    at Function.replaceChildWithTree (bundle.js:9341)
    at Object.dangerouslyReplaceNodeWithMarkup (bundle.js:72887)
    at Object.dangerouslyReplaceNodeWithMarkup [as replaceNodeWithMarkup] (bundle.js:15412)
    at ReactCompositeComponentWrapper._replaceNodeWithMarkup (bundle.js:74347)
    at ReactCompositeComponentWrapper._updateRenderedComponent (bundle.js:74337)
    at ReactCompositeComponentWrapper._performComponentUpdate (bundle.js:74287)
    at ReactCompositeComponentWrapper.updateComponent (bundle.js:74208)
    at ReactCompositeComponentWrapper.receiveComponent (bundle.js:74110)
    at Object.receiveComponent (bundle.js:8073)
    at ReactCompositeComponentWrapper._updateRenderedComponent (bundle.js:74317)
bundle.js:35181 Uncaught TypeError: Cannot read property 'name' of undefined
    at file:///opt/LBRY/resources/app/dist/js/bundle.js:35181:26
    at Array.map (native)
    at ChannelSection.render (file:///opt/LBRY/resources/app/dist/js/bundle.js:35180:29)
    at file:///opt/LBRY/resources/app/dist/js/bundle.js:74359:21
    at measureLifeCyclePerf (file:///opt/LBRY/resources/app/dist/js/bundle.js:73639:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (file:///opt/LBRY/resources/app/dist/js/bundle.js:74358:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:74385:32)
    at ReactCompositeComponentWrapper.performInitialMount (file:///opt/LBRY/resources/app/dist/js/bundle.js:73925:30)
    at ReactCompositeComponentWrapper.mountComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:73821:21)
    at Object.mountComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:7994:35)
bundle.js:9341 Uncaught TypeError: Cannot read property 'replaceChild' of null
    at Function.replaceChildWithTree (bundle.js:9341)
    at Object.dangerouslyReplaceNodeWithMarkup (bundle.js:72887)
    at Object.dangerouslyReplaceNodeWithMarkup [as replaceNodeWithMarkup] (bundle.js:15412)
    at ReactCompositeComponentWrapper._replaceNodeWithMarkup (bundle.js:74347)
    at ReactCompositeComponentWrapper._updateRenderedComponent (bundle.js:74337)
    at ReactCompositeComponentWrapper._performComponentUpdate (bundle.js:74287)
    at ReactCompositeComponentWrapper.updateComponent (bundle.js:74208)
    at ReactCompositeComponentWrapper.receiveComponent (bundle.js:74110)
    at Object.receiveComponent (bundle.js:8073)
    at ReactCompositeComponentWrapper._updateRenderedComponent (bundle.js:74317)
bundle.js:35181 Uncaught TypeError: Cannot read property 'name' of undefined
    at file:///opt/LBRY/resources/app/dist/js/bundle.js:35181:26
    at Array.map (native)
    at ChannelSection.render (file:///opt/LBRY/resources/app/dist/js/bundle.js:35180:29)
    at file:///opt/LBRY/resources/app/dist/js/bundle.js:74359:21
    at measureLifeCyclePerf (file:///opt/LBRY/resources/app/dist/js/bundle.js:73639:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (file:///opt/LBRY/resources/app/dist/js/bundle.js:74358:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:74385:32)
    at ReactCompositeComponentWrapper.performInitialMount (file:///opt/LBRY/resources/app/dist/js/bundle.js:73925:30)
    at ReactCompositeComponentWrapper.mountComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:73821:21)
    at Object.mountComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:7994:35)
bundle.js:9341 Uncaught TypeError: Cannot read property 'replaceChild' of null
    at Function.replaceChildWithTree (bundle.js:9341)
    at Object.dangerouslyReplaceNodeWithMarkup (bundle.js:72887)
    at Object.dangerouslyReplaceNodeWithMarkup [as replaceNodeWithMarkup] (bundle.js:15412)
    at ReactCompositeComponentWrapper._replaceNodeWithMarkup (bundle.js:74347)
    at ReactCompositeComponentWrapper._updateRenderedComponent (bundle.js:74337)
    at ReactCompositeComponentWrapper._performComponentUpdate (bundle.js:74287)
    at ReactCompositeComponentWrapper.updateComponent (bundle.js:74208)
    at ReactCompositeComponentWrapper.receiveComponent (bundle.js:74110)
    at Object.receiveComponent (bundle.js:8073)
    at ReactCompositeComponentWrapper._updateRenderedComponent (bundle.js:74317)
bundle.js:35181 Uncaught TypeError: Cannot read property 'name' of undefined
    at file:///opt/LBRY/resources/app/dist/js/bundle.js:35181:26
    at Array.map (native)
    at ChannelSection.render (file:///opt/LBRY/resources/app/dist/js/bundle.js:35180:29)
    at file:///opt/LBRY/resources/app/dist/js/bundle.js:74359:21
    at measureLifeCyclePerf (file:///opt/LBRY/resources/app/dist/js/bundle.js:73639:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (file:///opt/LBRY/resources/app/dist/js/bundle.js:74358:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:74385:32)
    at ReactCompositeComponentWrapper.performInitialMount (file:///opt/LBRY/resources/app/dist/js/bundle.js:73925:30)
    at ReactCompositeComponentWrapper.mountComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:73821:21)
    at Object.mountComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:7994:35)
bundle.js:9341 Uncaught TypeError: Cannot read property 'replaceChild' of null
    at Function.replaceChildWithTree (bundle.js:9341)
    at Object.dangerouslyReplaceNodeWithMarkup (bundle.js:72887)
    at Object.dangerouslyReplaceNodeWithMarkup [as replaceNodeWithMarkup] (bundle.js:15412)
    at ReactCompositeComponentWrapper._replaceNodeWithMarkup (bundle.js:74347)
    at ReactCompositeComponentWrapper._updateRenderedComponent (bundle.js:74337)
    at ReactCompositeComponentWrapper._performComponentUpdate (bundle.js:74287)
    at ReactCompositeComponentWrapper.updateComponent (bundle.js:74208)
    at ReactCompositeComponentWrapper.receiveComponent (bundle.js:74110)
    at Object.receiveComponent (bundle.js:8073)
    at ReactCompositeComponentWrapper._updateRenderedComponent (bundle.js:74317)
bundle.js:35181 Uncaught TypeError: Cannot read property 'name' of undefined
    at file:///opt/LBRY/resources/app/dist/js/bundle.js:35181:26
    at Array.map (native)
    at ChannelSection.render (file:///opt/LBRY/resources/app/dist/js/bundle.js:35180:29)
    at file:///opt/LBRY/resources/app/dist/js/bundle.js:74359:21
    at measureLifeCyclePerf (file:///opt/LBRY/resources/app/dist/js/bundle.js:73639:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (file:///opt/LBRY/resources/app/dist/js/bundle.js:74358:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:74385:32)
    at ReactCompositeComponentWrapper.performInitialMount (file:///opt/LBRY/resources/app/dist/js/bundle.js:73925:30)
    at ReactCompositeComponentWrapper.mountComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:73821:21)
    at Object.mountComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:7994:35)
bundle.js:9341 Uncaught TypeError: Cannot read property 'replaceChild' of null
    at Function.replaceChildWithTree (bundle.js:9341)
    at Object.dangerouslyReplaceNodeWithMarkup (bundle.js:72887)
    at Object.dangerouslyReplaceNodeWithMarkup [as replaceNodeWithMarkup] (bundle.js:15412)
    at ReactCompositeComponentWrapper._replaceNodeWithMarkup (bundle.js:74347)
    at ReactCompositeComponentWrapper._updateRenderedComponent (bundle.js:74337)
    at ReactCompositeComponentWrapper._performComponentUpdate (bundle.js:74287)
    at ReactCompositeComponentWrapper.updateComponent (bundle.js:74208)
    at ReactCompositeComponentWrapper.receiveComponent (bundle.js:74110)
    at Object.receiveComponent (bundle.js:8073)
    at ReactCompositeComponentWrapper._updateRenderedComponent (bundle.js:74317)
bundle.js:35181 Uncaught TypeError: Cannot read property 'name' of undefined
    at file:///opt/LBRY/resources/app/dist/js/bundle.js:35181:26
    at Array.map (native)
    at ChannelSection.render (file:///opt/LBRY/resources/app/dist/js/bundle.js:35180:29)
    at file:///opt/LBRY/resources/app/dist/js/bundle.js:74359:21
    at measureLifeCyclePerf (file:///opt/LBRY/resources/app/dist/js/bundle.js:73639:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (file:///opt/LBRY/resources/app/dist/js/bundle.js:74358:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:74385:32)
    at ReactCompositeComponentWrapper.performInitialMount (file:///opt/LBRY/resources/app/dist/js/bundle.js:73925:30)
    at ReactCompositeComponentWrapper.mountComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:73821:21)
    at Object.mountComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:7994:35)
bundle.js:9341 Uncaught TypeError: Cannot read property 'replaceChild' of null
    at Function.replaceChildWithTree (bundle.js:9341)
    at Object.dangerouslyReplaceNodeWithMarkup (bundle.js:72887)
    at Object.dangerouslyReplaceNodeWithMarkup [as replaceNodeWithMarkup] (bundle.js:15412)
    at ReactCompositeComponentWrapper._replaceNodeWithMarkup (bundle.js:74347)
    at ReactCompositeComponentWrapper._updateRenderedComponent (bundle.js:74337)
    at ReactCompositeComponentWrapper._performComponentUpdate (bundle.js:74287)
    at ReactCompositeComponentWrapper.updateComponent (bundle.js:74208)
    at ReactCompositeComponentWrapper.receiveComponent (bundle.js:74110)
    at Object.receiveComponent (bundle.js:8073)
    at ReactCompositeComponentWrapper._updateRenderedComponent (bundle.js:74317)
bundle.js:9341 Uncaught TypeError: Cannot read property 'replaceChild' of null
    at Function.replaceChildWithTree (bundle.js:9341)
    at Object.dangerouslyReplaceNodeWithMarkup (bundle.js:72887)
    at Object.dangerouslyReplaceNodeWithMarkup [as replaceNodeWithMarkup] (bundle.js:15412)
    at ReactCompositeComponentWrapper._replaceNodeWithMarkup (bundle.js:74347)
    at ReactCompositeComponentWrapper._updateRenderedComponent (bundle.js:74337)
    at ReactCompositeComponentWrapper._performComponentUpdate (bundle.js:74287)
    at ReactCompositeComponentWrapper.updateComponent (bundle.js:74208)
    at ReactCompositeComponentWrapper.receiveComponent (bundle.js:74110)
    at Object.receiveComponent (bundle.js:8073)
    at ReactCompositeComponentWrapper._updateRenderedComponent (bundle.js:74317)
bundle.js:35181 Uncaught TypeError: Cannot read property 'name' of undefined
    at file:///opt/LBRY/resources/app/dist/js/bundle.js:35181:26
    at Array.map (native)
    at ChannelSection.render (file:///opt/LBRY/resources/app/dist/js/bundle.js:35180:29)
    at file:///opt/LBRY/resources/app/dist/js/bundle.js:74359:21
    at measureLifeCyclePerf (file:///opt/LBRY/resources/app/dist/js/bundle.js:73639:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (file:///opt/LBRY/resources/app/dist/js/bundle.js:74358:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:74385:32)
    at ReactCompositeComponentWrapper.performInitialMount (file:///opt/LBRY/resources/app/dist/js/bundle.js:73925:30)
    at ReactCompositeComponentWrapper.mountComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:73821:21)
    at Object.mountComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:7994:35)`

## System Configuration

App | 0.15.1
-- | --
0.15.2
3.1.6
gfugfqpsfpsewz@divermail.com
 
Linux (Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial)

![lbry-crash](https://user-images.githubusercontent.com/22527575/30251118-b6562372-9651-11e7-9a7a-2fd6fa7de38a.gif)

**Comment by tzarebczan** [comment]
@oakey22 I can't seem to reproduce this on Windows with the latest v16RC7. Can you try it on the latest update? I'll give it a shot on Linux later on too.

**Comment by oakey22** [comment]
still happening for me on v16RC7, it seems to crash it when i click Publish and then off it straight away.

Could be linked in to #544

**Comment by oakey22** [comment]
this is now working since the fix for channel names,

https://github.com/lbryio/lbry-app/commit/4ed7d2cba9e7f6b2f0fccdd22bdc11ae85bfdaf5

**Comment by kauffj** [comment]
Yes, that trace is the same error as the issue with channel names. Going to close this.
