### ISSUE TITLE
Download fail of lbry://four

### ISSUE THREAD

**Issue by finer9** [lbryio/lbry-app#55]
### Steps to reproduce
1. Try to download lbry://four
2.
3.

### Expected behaviour
download

### Actual behaviour
hanging at connected
2017-04-24 22:55:26,101 INFO     lbrynet.core.Wallet:579: get claim info lbry://four#70a4753a0648d45346580c5c3dd5363e417d6a02
2017-04-24 22:55:26,101 INFO     lbrynet.lbrynet_daemon.Downloader:103: Download lbry://four status changed to initializing
2017-04-24 22:55:26,111 CRITICAL twisted:154: Unhandled error in Deferred:
2017-04-24 22:55:26,112 CRITICAL twisted:154: 
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages\lbrynet\lbrynet_daemon\Downloader.py", line 177, in download
KeyError: 'currency'
2017-04-24 22:55:26,313 INFO     lbrynet.lbrynet_daemon.Daemon:1016: Collected 0 lbry files

## System Configuration

 

- LBRY Daemon version:
daemon (lbrynet)	0.10.0
wallet (lbryum)	2.7.18
interface	0.10.0rc5
Platform	Windows (Windows-10-10.0.10586)
Installation ID	8eQ21PLjyYLSwM1EHxPB1RpzASaGmoQnpSaQrDu9PGafXrdmcEMsMoYz4yvZnB6zd1

**Comment by kaykurokawa** [comment]
Are you sure the latest lbry Daemon is being run here (10.0rc14 now) ? I'm not able to reproduce this.

**Comment by finer9** [comment]
Yes it should be the latest daemon.  I'll experiment more later.  Intuitively I thought it was related to claim takeover
