### ISSUE TITLE
Build fails on Fedora 26(4.12.12-300.fc26.x86_64)

### ISSUE THREAD

**Issue by Collinthegeek** [lbryio/lbry-app#583]
```
warning The case-insensitive file /home/cnorwood/Downloads/lbry-app/app/node_modules/npm/node_modules/JSONStream/test/fixtures/header_footer.json shouldn't be copied twice in one bulk copy 
(This first line appears a few dozen times for a bunch of different files)

[4/4] Building fresh packages...
[1/1] ⠁ keytar: gyp info spawn args   '-Goutput_dir=.' ]
[-/1] ⠁ waiting...
[-/1] ⠁ waiting...
[-/1] ⠁ waiting...
error /home/cnorwood/Downloads/lbry-app/app/node_modules/keytar: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/cnorwood/Downloads/lbry-app/app/node_modules/keytar
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.11.2 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/cnorwood/Downloads/lbry-app/app/node_modules/keytar/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/cnorwood/.node-gyp/6.11.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/cnorwood/.node-gyp/6.11.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules.bundled/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/cnorwood/Downloads/lbry-app/app/node_modules/keytar',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Package libsecret-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsecret-1.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libsecret-1', required by 'virtual:world', not found
gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.12.12-300.fc26.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/cnorwood/Downloads/lbry-app/app/node_modules/keytar
gyp ERR! node -v v6.11.2
```

**Comment by tzarebczan** [comment]
Looks like its due some missing prerequisites - please take a look at https://github.com/lbryio/lbry-app/blob/master/README.md - specifically the keytar step.

Once you do get it installed, you may run into https://github.com/lbryio/lbry-app/issues/572 - please see conversation regarding gnome keyring/authentication token requirements. We know this is an issue for any users and are tracking the root cause under: https://github.com/lbryio/lbry-app/issues/386

**Comment by MSFTserver** [comment]
it may also be these packages you could try along with @tzarebczan suggestion i also made a prebuild-dependecies script i can see if that works on fedora that should get everything you need to compile it no issues, so far it works on ubuntu and elemataryos but try this to:
```
sudo apt-get install build-essential 
```
and then 
```
sudo npm install -g node-gyp
```

**Comment by minamorcose** [comment]
```
sudo dnf install libsecret-devel

```
