### ISSUE TITLE
node-gyp rebuild fails during build

### ISSUE THREAD

**Issue by Dizeeee** [lbryio/lbry-app#812]
## The Issue
node-gyp rebuild fails during build

### Steps to reproduce
1. Run ./build.sh on Solus

### Expected behaviour
LBRY should build properly

### Actual behaviour
The following error is thrown
```
error /home/jack/github/lbry-app/src/main/node_modules/keytar: Command failed.
Exit code: 7
Command: node-gyp rebuild
Arguments: 
Directory: /home/jack/github/lbry-app/src/main/node_modules/keytar
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.1 | linux | x64
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: Cannot find module 'minipass'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:536:15)
gyp ERR! stack     at Function.Module._load (module.js:466:25)
gyp ERR! stack     at Module.require (module.js:579:17)
gyp ERR! stack     at require (internal/module.js:11:18)
gyp ERR! stack     at Object.<anonymous> (/usr/lib64/node_modules/npm/node_modules/node-gyp/node_modules/tar/lib/pack.js:25:18)
gyp ERR! stack     at Module._compile (module.js:635:30)
gyp ERR! stack     at Object.Module._extensions..js (module.js:646:10)
gyp ERR! stack     at Module.load (module.js:554:32)
gyp ERR! stack     at tryModuleLoad (module.js:497:12)
gyp ERR! stack     at Function.Module._load (module.js:489:3)
gyp ERR! System Linux 4.9.66-61.lts
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jack/github/lbry-app/src/main/node_modules/keytar
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! This is a bug in `node-gyp`.
```

## System Configuration

- LBRY Daemon version: N/A
- LBRY App version: Latest
- LBRY Installation ID: N/A
- Operating system: Solus

**Comment by tzarebczan** [comment]
Reached out to you on Discord. Try installing keytar/libsecrete - https://www.npmjs.com/package/keytar

**Comment by tzarebczan** [comment]
@Dizeeee per our conversation on github, it seems to be specific to failures building the keytar module which are most likely specific to the distro you have / node version. Will close this for now, please re-open if you find anything else, but I know you said you will be switching distros. 

```
> keytar@4.0.5 install /home/jack/github/lbry-app/node_modules/keytar
> node-gyp rebuild

gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: Cannot find module 'minipass'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:536:15)
gyp ERR! stack     at Function.Module._load (module.js:466:25)
gyp ERR! stack     at Module.require (module.js:579:17)
gyp ERR! stack     at require (internal/module.js:11:18)
gyp ERR! stack     at Object.<anonymous> (/usr/lib64/node_modules/npm/node_modules/node-gyp/node_modules/tar/lib/pack.js:25:18)
gyp ERR! stack     at Module._compile (module.js:635:30)
gyp ERR! stack     at Object.Module._extensions..js (module.js:646:10)
gyp ERR! stack     at Module.load (module.js:554:32)
gyp ERR! stack     at tryModuleLoad (module.js:497:12)
gyp ERR! stack     at Function.Module._load (module.js:489:3)
gyp ERR! System Linux 4.9.66-61.lts
gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jack/github/lbry-app/node_modules/keytar
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN lbry-app No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! keytar@4.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the keytar@4.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-05T04_52_32_573Z-debug.log
```
