### ISSUE TITLE
App errs after claim is abandoned from claim page, accessed via subscription page.

### ISSUE THREAD

**Issue by hackrush01** [lbryio/lbry-app#838]
## Steps to Reproduce
1. Subscribe you own channel
2. Go to a claim from subscription page
3. Abandon, and delete from comp using the Remove button
4. App shows green screen and console logs this error

## Logs

```js
/root/git-repos/lbry-repos/lbry-app/node_modules/redux-logger/dist/redux-logger.js:1  action ABANDON_CLAIM_STARTED @ 12:41:14.977
/root/git-repos/lbry-repos/lbry-app/node_modules/redux-logger/dist/redux-logger.js:1  action FILE_DELETE @ 12:41:14.979
/root/git-repos/lbry-repos/lbry-app/node_modules/redux-logger/dist/redux-logger.js:1  action BATCH_ACTIONS @ 12:41:14.982
/root/git-repos/lbry-repos/lbry-app/node_modules/redux-logger/dist/redux-logger.js:1  action FETCH_CHANNEL_CLAIMS_STARTED @ 12:41:15.076
/root/git-repos/lbry-repos/lbry-app/node_modules/redux-logger/dist/redux-logger.js:1  action FETCH_CHANNEL_CLAIMS_STARTED @ 12:41:15.080
/root/git-repos/lbry-repos/lbry-app/node_modules/redux-logger/dist/redux-logger.js:1  action FETCH_CHANNEL_CLAIMS_STARTED @ 12:41:15.084
/root/git-repos/lbry-repos/lbry-app/node_modules/redux-logger/dist/redux-logger.js:1  action HAS_FETCHED_SUBSCRIPTIONS @ 12:41:15.088
/root/git-repos/lbry-repos/lbry-app/node_modules/redux-logger/dist/redux-logger.js:1  action WINDOW_SCROLLED @ 12:41:15.095
/root/git-repos/lbry-repos/lbry-app/node_modules/react-redux/lib/components/connectAdvanced.js:258 Uncaught TypeError: Cannot read property 'name' of undefined
    at eval (webpack-internal:///./src/renderer/redux/selectors/subscriptions.js:64:19)
    at Array.map (native)
    at eval (webpack-internal:///./src/renderer/redux/selectors/subscriptions.js:63:35)
    at Array.forEach (native)
    at eval (webpack-internal:///./src/renderer/redux/selectors/subscriptions.js:46:22)
    at /root/git-repos/lbry-repos/lbry-app/node_modules/reselect/lib/index.js:76:25
    at /root/git-repos/lbry-repos/lbry-app/node_modules/reselect/lib/index.js:36:25
    at /root/git-repos/lbry-repos/lbry-app/node_modules/reselect/lib/index.js:90:33
    at /root/git-repos/lbry-repos/lbry-app/node_modules/reselect/lib/index.js:36:25
    at Function.select [as mapToProps] (webpack-internal:///./src/renderer/page/subscriptions/index.js:31:69)
    at mapToPropsProxy (/root/git-repos/lbry-repos/lbry-app/node_modules/react-redux/lib/connect/wrapMapToProps.js:54:92)
    at handleNewState (/root/git-repos/lbry-repos/lbry-app/node_modules/react-redux/lib/connect/selectorFactory.js:63:26)
    at handleSubsequentCalls (/root/git-repos/lbry-repos/lbry-app/node_modules/react-redux/lib/connect/selectorFactory.js:80:30)
    at pureFinalPropsSelector (/root/git-repos/lbry-repos/lbry-app/node_modules/react-redux/lib/connect/selectorFactory.js:85:32)
    at Object.runComponentSelector (/root/git-repos/lbry-repos/lbry-app/node_modules/react-redux/lib/components/connectAdvanced.js:43:25)
    at Connect.onStateChange (/root/git-repos/lbry-repos/lbry-app/node_modules/react-redux/lib/components/connectAdvanced.js:216:23)
/root/git-repos/lbry-repos/lbry-app/node_modules/react-dom/cjs/react-dom.development.js:9747 The above error occurred in the <Connect(_class)> component:
    in Connect(_class) (created by Router)
    in Router (created by Connect(Router))
    in Connect(Router) (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in div
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ /root/git-repos/lbry-repos/lbry-app/node_modules/react-dom/cjs/react-dom.development.js:9747
/root/git-repos/lbry-repos/lbry-app/node_modules/redux-logger/dist/redux-logger.js:1  action ABANDON_CLAIM_SUCCEEDED @ 12:41:23.087
subscriptions.js?495e:44 Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
    at eval (webpack-internal:///./src/renderer/redux/selectors/subscriptions.js:64:19)
    at Array.map (native)
    at eval (webpack-internal:///./src/renderer/redux/selectors/subscriptions.js:63:35)
    at Array.forEach (native)
    at eval (webpack-internal:///./src/renderer/redux/selectors/subscriptions.js:46:22)
    at /root/git-repos/lbry-repos/lbry-app/node_modules/reselect/lib/index.js:76:25
    at /root/git-repos/lbry-repos/lbry-app/node_modules/reselect/lib/index.js:36:25
    at /root/git-repos/lbry-repos/lbry-app/node_modules/reselect/lib/index.js:90:33
    at /root/git-repos/lbry-repos/lbry-app/node_modules/reselect/lib/index.js:36:25
    at Function.select [as mapToProps] (webpack-internal:///./src/renderer/page/subscriptions/index.js:31:69)
    at mapToPropsProxy (/root/git-repos/lbry-repos/lbry-app/node_modules/react-redux/lib/connect/wrapMapToProps.js:54:92)
    at handleNewState (/root/git-repos/lbry-repos/lbry-app/node_modules/react-redux/lib/connect/selectorFactory.js:63:26)
    at handleSubsequentCalls (/root/git-repos/lbry-repos/lbry-app/node_modules/react-redux/lib/connect/selectorFactory.js:80:30)
    at pureFinalPropsSelector (/root/git-repos/lbry-repos/lbry-app/node_modules/react-redux/lib/connect/selectorFactory.js:85:32)
    at Object.runComponentSelector (/root/git-repos/lbry-repos/lbry-app/node_modules/react-redux/lib/components/connectAdvanced.js:43:25)
    at Connect.onStateChange (/root/git-repos/lbry-repos/lbry-app/node_modules/react-redux/lib/components/connectAdvanced.js:216:23)
```

**Comment by tzarebczan** [comment]
Another user ran into a similar situation, here is the log: https://pastebin.com/KxU4Ryd9.

I'll try to get this reproduced. I tried once in the past but was not successful.
