### ISSUE TITLE
Linux stable .deb app doesn't launch

### ISSUE THREAD

**Issue by fassn** [lbryio/lbry-app#878]
### Steps to reproduce
1. Launch the app through "lbry" in command-line

### Behaviour
**Last lines of the log:**
```
2017-12-15 22:21:24,990 INFO     lbrynet.core.Wallet:1224: Stopped connection to lbryum server
2017-12-15 22:21:24,991 INFO     lbrynet.core.BlobManager:46: Stopping disk blob manager.
2017-12-15 22:21:24,992 INFO     lbrynet.core.Session:324: Unsetting upnp for session
2017-12-15 22:21:24,993 INFO     lbrynet.dht.protocol:445: Stopping DHT
2017-12-15 22:21:24,993 INFO     lbrynet.dht.protocol:461: DHT stopped
Unhandled error in Deferred:
2017-12-15 22:21:24,994 CRITICAL twisted:154: Unhandled error in Deferred:

2017-12-15 22:21:24,994 CRITICAL twisted:154: 
Traceback (most recent call last):
  File "site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
  File "site-packages/lbrynet/file_manager/EncryptedFileManager.py", line 117, in _start_lbry_files
  File "site-packages/lbrynet/core/sqlite_helpers.py", line 19, in wrapper
  File "site-packages/lbrynet/file_manager/EncryptedFileManager.py", line 306, in _get_all_lbry_files
AttributeError: 'NoneType' object has no attribute 'runQuery'
2017-12-15 22:21:26,003 INFO     lbrynet.core.Session:338: Removed UPnP redirect for TCP 3333.
2017-12-15 22:21:26,008 INFO     lbrynet.core.Session:338: Removed UPnP redirect for UDP 4444.
The daemon has exited.
Did not request daemon stop, so quitting in 5 seconds.
Quitting.
```

## System Configuration
- Operating system:
Ubuntu 16.04

Fresh install of Ubuntu I haven't installed much yet, that might explain if there is library missing or something... Please enlighten. :)

**Comment by tzarebczan** [comment]
Does this happen everytime you launch? Can you give it another try?

Please post the entire log as well, thanks!

**Comment by fassn** [comment]
Yes it did the 4 or 5 times I tried to run it.

**Comment by fassn** [comment]
Nevermind, it was probably due to port 3333 being used by Claymore in the meantime.

I git cloned the lbry-app repo, launched it and it worked as soon as I closed Claymore.

**Comment by tzarebczan** [comment]
Ah great, I think there should be a mention of that in the log. Glad you got it figured out!
